// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelCycle.Data;

#nullable disable

namespace ModelCycle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127140822_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ModelCycle.Models.ModelImageLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelWeightId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrainingImageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelWeightId");

                    b.HasIndex("TrainingImageId");

                    b.ToTable("ModelImageLinks");
                });

            modelBuilder.Entity("ModelCycle.Models.ModelWeights", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoldenFakeToRealMisclassifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldenRealToFakeMisclassifications")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GoldenTestAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("GoldenTestF1Score")
                        .HasColumnType("REAL");

                    b.Property<double>("GoldenTestPrecision")
                        .HasColumnType("REAL");

                    b.Property<double>("GoldenTestRecall")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeployed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinioObjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NewImagesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplayBufferCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValidationAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("ValidationF1Score")
                        .HasColumnType("REAL");

                    b.Property<double>("ValidationPrecision")
                        .HasColumnType("REAL");

                    b.Property<double>("ValidationRecall")
                        .HasColumnType("REAL");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelWeights");
                });

            modelBuilder.Entity("ModelCycle.Models.TrainingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaImageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ModelConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAiVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserRealVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrainingImages");
                });

            modelBuilder.Entity("ModelCycle.Models.ModelImageLink", b =>
                {
                    b.HasOne("ModelCycle.Models.ModelWeights", "ModelWeight")
                        .WithMany("ImageLinks")
                        .HasForeignKey("ModelWeightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelCycle.Models.TrainingImage", "TrainingImage")
                        .WithMany()
                        .HasForeignKey("TrainingImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelWeight");

                    b.Navigation("TrainingImage");
                });

            modelBuilder.Entity("ModelCycle.Models.ModelWeights", b =>
                {
                    b.Navigation("ImageLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
