apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: devpass
  MONGO_DB: aiclipse
  MONGO_URI: "mongodb://root:devpass@mongo-srv:27017/?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-sec
type: Opaque
stringData:
  REDIS_PASSWORD: devpass
  REDIS_HOST: redis-srv
  REDIS_PORT: "6379"
  REDIS_URI: "redis://:devpass@redis-srv:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-sec
type: Opaque
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: devpassai
  S3_ENDPOINT: "http://s3-srv:9000"
  S3_PUBLIC_ENDPOINT: "http://storage.aiclipse.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-sec
type: Opaque
stringData:
  JWT_KEY: 08a4063766400145bd0db33f9ccb58fe02b69276528c7162096e9905cc400695
  DETECTION_TOKEN_SECRET: 2c1112bcbb6abfe811c08b1890a7bbd08ae38a4b5a2ce602c67035fb36ea3563
---