apiVersion: v1
kind: Secret
metadata: { name: redis-sec }
type: Opaque
stringData: { REDIS_PASSWORD: devpass }
---
apiVersion: v1
kind: Secret
metadata: { name: mongo-sec }
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: devpass
---
apiVersion: v1
kind: Secret
metadata: { name: app-mongo-sec }
type: Opaque
stringData:
  MONGO_URI: mongodb://root:devpass@mongo-srv:27017/aiclipse?authSource=admin
---
apiVersion: v1
kind: Secret
metadata: { name: s3-sec }
type: Opaque
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: devpass
---
apiVersion: v1
kind: Secret
metadata: { name: jwt-sec }
type: Opaque
stringData:
  JWT_KEY: devjwtsecret
