apiVersion: v1
kind: Secret
metadata:
  name: s3-sec
type: Opaque
stringData:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: devpassai
  
  S3_ENDPOINT: "http://s3-srv:9000"
  S3_PUBLIC_ENDPOINT: "http://localhost:9000"