import test from "node:test";
import assert from "node:assert/strict";
import {
  ensureCommunityIndexes,
  resetCommunityIndexesForTests,
} from "../lib/mongo/indexes.js";

function makeCollectionRecorder(existingIndexes = []) {
  const calls = [];
  const indexes = [...existingIndexes];

  return {
    calls,
    async createIndex(key, options = {}) {
      calls.push({ key, options });
      indexes.push({
        name: options.name || `created_${calls.length}`,
        key,
        unique: options.unique,
        expireAfterSeconds: options.expireAfterSeconds,
      });
    },
    listIndexes() {
      return {
        async toArray() {
          return indexes;
        },
      };
    },
  };
}

function makeNamespaceMissingCollectionRecorder() {
  const calls = [];
  const indexes = [];

  return {
    calls,
    async createIndex(key, options = {}) {
      calls.push({ key, options });
      indexes.push({
        name: options.name || `created_${calls.length}`,
        key,
        unique: options.unique,
        expireAfterSeconds: options.expireAfterSeconds,
      });
    },
    listIndexes() {
      return {
        async toArray() {
          const error = new Error("ns not found");
          error.codeName = "NamespaceNotFound";
          throw error;
        },
      };
    },
  };
}

function makeDbRecorder(overrides = {}) {
  const collections = new Map();

  return {
    collection(name) {
      if (!collections.has(name)) {
        collections.set(name, makeCollectionRecorder(overrides[name] || []));
      }
      return collections.get(name);
    },
  };
}

test.beforeEach(() => {
  resetCommunityIndexesForTests();
});

test("ensureCommunityIndexes creates the critical runtime-owned indexes", async () => {
  const db = makeDbRecorder();

  await ensureCommunityIndexes(db);

  const names = [
    ...db.collection("community.posts").calls.map((call) => `community.posts:${call.options.name || ""}`),
    ...db.collection("community.comments").calls.map((call) => `community.comments:${call.options.name || ""}`),
    ...db.collection("community.votes").calls.map((call) => `community.votes:${call.options.name || ""}`),
    ...db.collection("community.clicks").calls.map((call) => `community.clicks:${call.options.name || ""}`),
    ...db.collection("community.notifications").calls.map((call) => `community.notifications:${call.options.name || ""}`),
  ];

  assert.ok(names.includes("community.posts:uniq_post_id"));
  assert.ok(names.includes("community.posts:by_image_id"));
  assert.ok(names.includes("community.comments:uniq_comment_id"));
  assert.ok(names.includes("community.votes:uniq_post_user_vote"));
  assert.ok(names.includes("community.clicks:uniq_post_user_click"));
  assert.ok(names.includes("community.notifications:notif_collapse_key"));
  assert.ok(names.includes("community.notifications:notif_ttl_created"));
});

test("ensureCommunityIndexes reuses equivalent legacy notification indexes with old autogenerated names", async () => {
  const db = makeDbRecorder({
    "community.notifications": [
      {
        name: "recipient_user_id_1_is_read_1_last_event_at_-1",
        key: { recipient_user_id: 1, is_read: 1, last_event_at: -1 },
      },
      {
        name: "recipient_user_id_1_last_event_at_-1",
        key: { recipient_user_id: 1, last_event_at: -1 },
      },
    ],
  });

  await ensureCommunityIndexes(db);

  const notificationIndexNames = db
    .collection("community.notifications")
    .calls
    .map((call) => call.options.name);

  assert.ok(!notificationIndexNames.includes("notif_by_recipient_read"));
  assert.ok(!notificationIndexNames.includes("notif_by_recipient_latest"));
  assert.ok(notificationIndexNames.includes("notif_collapse_key"));
  assert.ok(notificationIndexNames.includes("notif_ttl_created"));
});

test("ensureCommunityIndexes creates indexes on fresh collections without failing listIndexes", async () => {
  const collections = new Map();
  const db = {
    collection(name) {
      if (!collections.has(name)) {
        collections.set(name, makeNamespaceMissingCollectionRecorder());
      }
      return collections.get(name);
    },
  };

  await ensureCommunityIndexes(db);

  assert.ok(db.collection("community.posts").calls.length > 0);
  assert.ok(db.collection("community.notifications").calls.length > 0);
});
