apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-depl
spec:
  replicas: 1
  selector: { matchLabels: { app: billing } }
  template:
    metadata: { labels: { app: billing } }
    spec:
      containers:
        - name: billing
          image: aiclipse/billing
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef: { name: app-mongo-sec, key: MONGO_URI }
          ports: [{ name: http, containerPort: 3000 }]
          readinessProbe:
            { httpGet: { path: /healthz, port: 3000 }, initialDelaySeconds: 5 }
          livenessProbe:
            { httpGet: { path: /healthz, port: 3000 }, initialDelaySeconds: 15 }
          resources:
            requests: { cpu: "25m", memory: "64Mi" }
            limits: { cpu: "200m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: billing-srv
spec:
  type: ClusterIP
  selector: { app: billing }
  ports: [{ name: http, port: 3000, targetPort: 3000 }]
