apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-depl
spec:
  replicas: 1
  selector:
    matchLabels: { app: detector }
  template:
    metadata:
      labels: { app: detector }
    spec:
      containers:
        - name: detector
          image: aiclipse/detector
          ports:
            - { containerPort: 3000, name: http }
          env:
            - name: MONGO_URI
              valueFrom: { secretKeyRef: { name: mongo-sec, key: MONGO_URI } }
            - name: MONGO_DB
              valueFrom: { secretKeyRef: { name: mongo-sec, key: MONGO_DB } }
            - name: REDIS_URI
              valueFrom: { secretKeyRef: { name: redis-sec, key: REDIS_URI } }
            - name: STREAM
              value: "jobs"
            - name: GROUP
              value: "detector"
            - name: JOBS_URI
              value: "http://jobs-srv:3000"
          readinessProbe:
            httpGet: { path: /healthz, port: 3000, scheme: HTTP }
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet: { path: /healthz, port: 3000, scheme: HTTP }
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
          startupProbe:
            httpGet: { path: /healthz, port: 3000, scheme: HTTP }
            periodSeconds: 1
            failureThreshold: 60 
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits: { cpu: "1", memory: "1Gi" }
---
apiVersion: v1
kind: Service
metadata:
  name: detector-srv
spec:
  type: ClusterIP
  selector: { app: detector }
  ports:
    - { name: http, port: 3000, targetPort: 3000 }
