apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-depl
spec:
  replicas: 1
  selector: { matchLabels: { app: jobs } }
  template:
    metadata: { labels: { app: jobs } }
    spec:
      containers:
        - name: jobs
          image: aiclipse/jobs
          ports: [{ containerPort: 3000, name: http }]
          env:
            - name: MONGO_URI
              valueFrom: { secretKeyRef: { name: mongo-sec, key: MONGO_URI } }
            - name: MONGO_DB
              valueFrom: { secretKeyRef: { name: mongo-sec, key: MONGO_DB } }
            - name: REDIS_URI
              valueFrom: { secretKeyRef: { name: redis-sec, key: REDIS_URI } }
            - name: STREAM
              value: "jobs"
            - name: BILLING_URI
              value: "http://billing-srv:3000"
          readinessProbe:
            httpGet: { path: /healthz, port: 3000, scheme: HTTP }
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet: { path: /healthz, port: 3000, scheme: HTTP }
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
          startupProbe:
            httpGet: { path: /healthz, port: 3000, scheme: HTTP }
            periodSeconds: 1
            failureThreshold: 60 
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits: { cpu: "300m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-srv
spec:
  type: ClusterIP
  selector: { app: jobs }
  ports: [{ name: http, port: 3000, targetPort: 3000 }]
