apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-cycle-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-cycle
  template:
    metadata:
      labels:
        app: model-cycle
    spec:
    #To wait for minio, model cycle will have a dependency and requires minio to be started before we spin it up
      initContainers:
          - name: wait-for-minio
            image: busybox
            command: ['sh', '-c', 'until nc -z minio 9000; do echo waiting for minio; sleep 2; done;']
      containers:
        - name: model-cycle
          image: aiclipse/model-cycle
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom: { secretKeyRef: { name: mongo-sec, key: MONGO_URI } }
            - name: MONGO_DB
              valueFrom: { secretKeyRef: { name: mongo-sec, key: MONGO_DB } }
            - name: S3_ENDPOINT 
              valueFrom: { secretKeyRef: { name: s3-sec, key: S3_ENDPOINT } } 
            - name: S3_PUBLIC_ENDPOINT
              valueFrom: { secretKeyRef: { name: s3-sec, key: S3_PUBLIC_ENDPOINT } } 
            - name: AWS_ACCESS_KEY_ID 
              valueFrom: { secretKeyRef: { name: s3-sec, key: MINIO_ROOT_USER } } 
            - name: AWS_SECRET_ACCESS_KEY 
              valueFrom: { secretKeyRef: { name: s3-sec, key: MINIO_ROOT_PASSWORD } }
            - name: MINIO_BUCKET_NAME
              value: "model-cycle-storage"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            periodSeconds: 1
            failureThreshold: 60
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: model-cycle-srv
spec:
  type: ClusterIP
  selector:
    app: model-cycle
  ports:
    - name: http
      port: 3000
      targetPort: 3000
