{
 "title": "Logs",
 "tags": [ "logs" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\"} \r\n|~ \"(?i)(error|exception)\"\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "crash patterns",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\"} |~ \"(?i)(oomkilled|killed|exit code|panic|fatal|traceback)\""
    }
   ]
  },
  {
   "title": "auth-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"auth-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "billing-depl",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"billing-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "clinet-depl",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"client-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "community-depl",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"community-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "detector-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"detector-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "gateway-depl",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"gateway-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "media-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"media-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "model-cycle-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"model-cycle-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "vote-flush-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"vote-flush-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "comments-flush-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"comments-flush-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  },
  {
   "title": "click-flush-depl",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{namespace=\"default\", pod=~\"click-flush-depl-.*\"}\r\n| json\r\n| line_format \"{{.log}}\""
    }
   ]
  }
 ]
}